---
title: "plotting1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## plot 1

```{r}
# download and unzip the file
library(downloader)
url <- "https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip"
download(url, dest = "power.zip", mode = "wb") 
unzip("power.zip", exdir = "./")
```
```{r}
# read in the data
power <- read.table(file = "household_power_consumption.txt", header = TRUE, sep = ";")
```

```{r}
# convert Date column to date class
library(lubridate)
power$Date <- dmy(power$Date)
class(power$Date)
```

```{r}
# filter for given dates
library(dplyr)
power <- filter(power, Date >= "2007-02-01" & Date <= "2007-02-02")
```

```{r}
# remove missing values
power <- filter(power, Global_active_power != "?")
```

```{r}
# convert factor to character and then numeric
power$Global_active_power <- as.numeric(as.character(power$Global_active_power))
class(power$Global_active_power)
```

```{r}
hist(power$Global_active_power, col = "red", main = "Global Active Power", xlab = "Global Active Power (kilowatts)")
```

## plot 2

```{r}
# combine date and time
power$datetime <- ymd_hms(paste(power$Date, power$Time))
```


```{r}
View(power)
```

```{r}
plot(x = power$datetime, y = power$Global_active_power, type = "l", ylab = "Global Active Power (kilowatts)", xlab = "")
```

## plot 3

```{r}
plot(x = power$datetime, power$Sub_metering_1, type = "l", ylab = "Energy sub metering", xlab = "")
lines(x = power$datetime, power$Sub_metering_2, type = "l", col = "red")
lines(x = power$datetime, power$Sub_metering_3, type = "l", col = "blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty = c(1,1,1), col = c("black", "red", "blue"))
```

red data?

## plot4

```{r}
power$Voltage <- as.numeric(as.character(
                              power$Voltage))
```


```{r}
plot(x = power$datetime, y = power$Voltage, 
     type = "l", 
     ylab = "Voltage", 
     xlab = "datetime")
```


```{r}
power$Voltage <- as.numeric(as.character(
                              power$Voltage))
```


```{r}
plot(x = power$datetime, y = power$Global_reactive_power, 
     type = "l", 
     ylab = "Global_reactive_power",
     xlab = "datetime")
```


```{r}
# load libraries
library(downloader)
library(lubridate)
library(dplyr)

# download and unzip the file
url <- "https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip"
download(url, dest = "power.zip", mode = "wb") 
unzip("power.zip", exdir = "./")

# read in the data
classes <- c("character", "character", "numeric", "numeric",
             "numeric", "numeric", "numeric", "numeric",
             "numeric")
power1 <- read.table(file = "household_power_consumption.txt",
                     na.strings = "?"
                     colClasses = classes, 
                     header = TRUE, sep = ";")

# convert Date column to date class
power$Date <- dmy(power$Date)

# combine date and time
power$datetime <- ymd_hms(paste(power$Date, power$Time))

# filter for given dates
power <- filter(power, Date >= "2007-02-01" 
                & Date <= "2007-02-02")

# remove missing values
power <- filter(power, Global_active_power != "?")

# convert factor to character and then numeric
power$Global_active_power <- as.numeric(as.character(
  power$Global_active_power))
power$Global_reactive_power <- as.numeric(as.character(
  power$Global_reactive_power))
power$Sub_metering_2 <- as.numeric(as.character(
  power$Sub_metering_2))
power$Sub_metering_1 <- as.numeric(as.character(
  power$Sub_metering_1))

# create the plot
png("plot4.png")
par(mfrow = c(2,2))
# plot2 in top left
plot(x = power$datetime, y = power$Global_active_power, 
     type = "l", 
     ylab = "Global Active Power (kilowatts)", 
     xlab = "")

# top left plot
plot(x = power$datetime, y = power$Voltage, 
     type = "l", 
     ylab = "Voltage", 
     xlab = "datetime")

# plot3 in bottom left with legend border removed
plot(x = power$datetime, power$Sub_metering_1, type = "l", 
     ylab = "Energy sub metering", xlab = "")
lines(x = power$datetime, power$Sub_metering_2, type = "l", 
      col = "red")
lines(x = power$datetime, power$Sub_metering_3, type = "l", 
      col = "blue")
legend("topright", 
       c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), 
       lty = c(1,1,1), col = c("black", "red", "blue"),
       bty = "n")

# bottom right plot
plot(x = power$datetime, y = power$Global_reactive_power, 
     type = "l", 
     ylab = "Global_reactive_power",
     xlab = "datetime")
dev.off()
```

```{r}
# create classes vector
classes <- c("character", "character", "numeric", "numeric",
             "numeric", "numeric", "numeric", "numeric",
             "numeric")

# read in the data
hpc <- read.table(file = "household_power_consumption.txt",
                     na.strings = "?",
                     colClasses = classes, 
                     header = TRUE, sep = ";")

# parse date and time together
hpc$datetime <- dmy_hms(paste(hpc$Date, hpc$Time))

# convert Date to Date and filter for given dates
hpc$Date <- dmy(hpc$Date)
hpc <- filter(hpc, Date >= "2007-02-01" 
              & Date <= "2007-02-02")

# send to device
png("plot41.png")

# create frame
par(mfrow = c(2,2))
# plot2 in top left
with(hpc, plot(x = datetime, y = Global_active_power, 
     type = "l", 
     ylab = "Global Active Power (kilowatts)", 
     xlab = ""))

# top left plot
with(hpc, plot(x = datetime, y = Voltage, 
     type = "l", 
     ylab = "Voltage", 
     xlab = "datetime"))

# plot3 in bottom left with legend border removed
with(hpc, plot(x = datetime, y = Sub_metering_1, 
               type = "l", 
               ylab = "Energy sub metering", 
               xlab = ""))
with(hpc, lines(x = datetime, y = Sub_metering_2, 
                type = "l", 
                col = "red"))
with(hpc, lines(x = datetime, y = Sub_metering_3, 
                type = "l", 
                col = "blue"))
legend("topright", 
       c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), 
       lty = c(1,1,1), col = c("black", "red", "blue"),
       bty = "n")

# bottom right plot
with(hpc, plot(x = datetime, y = Global_reactive_power, 
     type = "l", 
     ylab = "Global_reactive_power",
     xlab = "datetime"))

# close device
dev.off()
```





